### ISSUE TITLE
Document the difference between your fork and Atomic

### ISSUE THREAD

**Issue by KOLANICH** [jcjordyn130/simpleirc#2]

**Comment by jcjordyn130** [comment]
Fixed in 11722b763690af0890bc7b5182f0b673a4a28f85 (Added the diffrences between Simple IRC and Atmoic)

**Comment by 5moufl** [comment]
is there a way to import settings from atomic @jcjordyn130 ?

**Comment by jcjordyn130** [comment]
@5moufl no, atmoic would need to be able to export them. also please create another issue instead of commenting on old ones.

**Comment by 5moufl** [comment]
my bad. I did not think it needed a thread of its own and that the two were
(kinda) related.

**Comment by jcjordyn130** [comment]
@5moufl it's okay :)

**Comment by KOLANICH** [comment]
>is there a way to import settings from atomic?

Have you tried to just copy its data folder (root is required, you will also need to change owner with ```chown -R```)?

**Comment by KOLANICH** [comment]
@jcjordyn130, 
>Logging support

Atomic has it: Settings->Misc->Debug IRC traffic

>A black and white theme

Atomic has it: Settings->Interface->Use dark colorscheme

The rest of features are really not present in Atomic. BTW, does ```/join``` work in your client? In Atomic it doesn't.

**Comment by jcjordyn130** [comment]
@KOLANICH That isn't what I mean by logging, logging means logging to disk not the android debug logs. /join works but not with ZNC or most other commands for some reason. also the black and white theme is added as I changed the default theme. :P

**Comment by KOLANICH** [comment]
Thank you.

**Comment by jcjordyn130** [comment]
@KOLANICH welcome. :)
