### ISSUE TITLE
Server not honored in network

### ISSUE THREAD

**Issue by asterismo** [jcjordyn130/simpleirc#6]
Hey something happened in the lastest update that all networks are connecting to the last network server in the bottom. any ideas?

**Comment by jcjordyn130** [comment]
Can you tell me what version?

**Comment by asterismo** [comment]
1.6

**Comment by jcjordyn130** [comment]
There is a race condition in Version 1.6, please try Version 1.8. Which you can find here: [https://github.com/jcjordyn130/simpleirc/blob/master/apks/SimpleIRC-1.8-release.apk?raw=true](https://github.com/jcjordyn130/simpleirc/blob/master/apks/SimpleIRC-1.8-release.apk?raw=true)
