### ISSUE TITLE
unable to download apk

### ISSUE THREAD

**Issue by ghost** [jcjordyn130/simpleirc#7]
i am unable to download apk from apk folder on github. i have tried to download using couple of browsers & download manager.

is this default behaviour ?

https://github.com/jcjordyn130/simpleirc/tree/master/apks

error while downloading: This file is too big to show. Sorry!

**Comment by jcjordyn130** [comment]
That's a issue with the github mobile site, in the meantime use this link: https://github.com/jcjordyn130/simpleirc/blob/master/apks/apknamehere?raw=true

**Comment by ghost** [comment]
the link works like a charm.
i have downloaded 1.8 version.

thank you.

**Comment by jcjordyn130** [comment]
Closing. :)
